# Generated by Django 2.2.7 on 2020-01-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
